namespace Auuueser.EnemyHealthBars.Core.Configuration;

public static class ConfigTextCatalog
{
    public static ConfigTexts Get(ConfigLanguage language)
    {
        return language == ConfigLanguage.Chinese ? Chinese : English;
    }

    private static readonly ConfigTexts English = new(
        generalSection: "General",
        visibilitySection: "Visibility",
        performanceSection: "Performance",
        diagnosticsSection: "Diagnostics",
        layoutSection: "Layout",
        debugSection: "Debug",
        modDescription: "Client-side enemy health bars. All settings apply immediately after saving.",
        enabledName: "Enabled",
        showWhenFullHealthName: "Show full-health enemies",
        showInvulnerableEnemiesName: "Show invulnerable enemies",
        maxHealthModeName: "Max health mode",
        maxDistanceName: "Maximum display distance",
        scanIntervalName: "Scan interval",
        diagnosticsEnabledName: "Enable diagnostic logs",
        diagnosticsLogIntervalName: "Diagnostic log interval",
        verticalOffsetName: "Vertical offset",
        barWidthName: "Bar width",
        barHeightName: "Bar height",
        worldScaleName: "World scale",
        displayModeName: "Display mode",
        showHealthNumbersName: "Show health numbers",
        healthTextFormatName: "Health text format",
        showEnemyNameName: "Show enemy name",
        sideBarWidthName: "Side bar width",
        sideBarHeightName: "Side bar height",
        sideBarHorizontalOffsetName: "Side bar horizontal offset",
        debugEnabledName: "Enable debug mode",
        debugShowFullHealthEnemiesName: "Show full-health enemies",
        debugDiagnosticsEnabledName: "Enable diagnostic logs",
        debugDiagnosticsLogIntervalName: "Diagnostic log interval",
        debugShowTestBarName: "Show test bar",
        enabledDescription: "Enable enemy health bars. Applied immediately.",
        showWhenFullHealthDescription: "Show bars for enemies that have not taken damage yet. Applied immediately.",
        showInvulnerableEnemiesDescription: "Show bars for enemies whose EnemyType cannot die. Applied immediately.",
        maxHealthModeDescription: "How maximum health is resolved: VanillaStrict keeps base-game defaults, Adaptive uses observed instance health, Hybrid keeps special vanilla rules and adapts to observed modded health. Applied immediately.",
        maxDistanceDescription: "Maximum distance for rendering enemy health bars. Set 0 or below for no distance limit. Applied immediately.",
        scanIntervalDescription: "Seconds between enemy list refreshes. Applied immediately.",
        diagnosticsEnabledDescription: "Log low-frequency health bar scan counters for troubleshooting. Applied immediately.",
        diagnosticsLogIntervalDescription: "Seconds between diagnostic log lines when diagnostics are enabled. Applied immediately.",
        verticalOffsetDescription: "World-space offset above the enemy eye transform. Applied immediately.",
        barWidthDescription: "World-space canvas width before scale is applied. Applied immediately.",
        barHeightDescription: "World-space canvas height before scale is applied. Applied immediately.",
        worldScaleDescription: "World-space canvas scale. Applied immediately.",
        displayModeDescription: "Health bar layout mode: horizontal bar, side vertical bar, or numbers only. Applied immediately.",
        showHealthNumbersDescription: "Show current and max health text on enemy health bars. Applied immediately.",
        healthTextFormatDescription: "Health text format: Current / max, current only, or percent only. Applied immediately.",
        showEnemyNameDescription: "Show the enemy name beside the health number text. Applied immediately.",
        sideBarWidthDescription: "Vertical side-bar width before scale is applied. Applied immediately.",
        sideBarHeightDescription: "Vertical side-bar height before scale is applied. Applied immediately.",
        sideBarHorizontalOffsetDescription: "Horizontal offset used by side vertical bar mode. Applied immediately.",
        debugEnabledDescription: "Enable test-only debug features. Keep this disabled during normal play. Applied immediately.",
        debugShowFullHealthEnemiesDescription: "Debug only: show bars for full-health enemies to verify enemy tracking. Requires debug mode. Applied immediately.",
        debugDiagnosticsEnabledDescription: "Debug only: log low-frequency runtime, camera, scan, and active-bar counters. Requires debug mode. Applied immediately.",
        debugDiagnosticsLogIntervalDescription: "Debug only: seconds between diagnostic log lines. Applied immediately.",
        debugShowTestBarDescription: "Debug only: render a fixed test health bar in front of the active camera. Requires debug mode. Applied immediately.");

    private static readonly ConfigTexts Chinese = new(
        generalSection: "通用",
        visibilitySection: "可见性",
        performanceSection: "性能",
        diagnosticsSection: "诊断",
        layoutSection: "布局",
        debugSection: "调试",
        modDescription: "显示怪物血条的纯客户端模组。所有配置保存后立即生效。",
        enabledName: "启用",
        showWhenFullHealthName: "显示满血怪物",
        showInvulnerableEnemiesName: "显示不可死亡怪物",
        maxHealthModeName: "最大血量模式",
        maxDistanceName: "最大显示距离",
        scanIntervalName: "扫描间隔",
        diagnosticsEnabledName: "启用诊断日志",
        diagnosticsLogIntervalName: "诊断日志间隔",
        verticalOffsetName: "垂直偏移",
        barWidthName: "血条宽度",
        barHeightName: "血条高度",
        worldScaleName: "世界缩放",
        displayModeName: "显示模式",
        showHealthNumbersName: "显示血量数字",
        healthTextFormatName: "血量文字格式",
        showEnemyNameName: "显示怪物名称",
        sideBarWidthName: "侧边血条宽度",
        sideBarHeightName: "侧边血条高度",
        sideBarHorizontalOffsetName: "侧边血条水平偏移",
        debugEnabledName: "启用调试模式",
        debugShowFullHealthEnemiesName: "显示满血怪物",
        debugDiagnosticsEnabledName: "启用诊断日志",
        debugDiagnosticsLogIntervalName: "诊断日志间隔",
        debugShowTestBarName: "显示测试血条",
        enabledDescription: "启用怪物血条。保存后立即生效。",
        showWhenFullHealthDescription: "显示未受伤怪物的满血血条。保存后立即生效。",
        showInvulnerableEnemiesDescription: "显示 EnemyType 标记为不可死亡的怪物血条。保存后立即生效。",
        maxHealthModeDescription: "最大血量计算方式：VanillaStrict 使用原版默认值，Adaptive 使用实际观察到的怪物血量，Hybrid 保留原版特殊规则并适应模组修改后的血量。保存后立即生效。",
        maxDistanceDescription: "血条最大显示距离。设置为 0 或更低表示不限制距离。保存后立即生效。",
        scanIntervalDescription: "刷新怪物列表的间隔秒数。保存后立即生效。",
        diagnosticsEnabledDescription: "输出低频血条扫描计数日志，用于排查问题。保存后立即生效。",
        diagnosticsLogIntervalDescription: "启用诊断时，两次诊断日志之间的秒数。保存后立即生效。",
        verticalOffsetDescription: "血条相对怪物眼部锚点的世界空间高度偏移。保存后立即生效。",
        barWidthDescription: "应用缩放前的世界空间血条宽度。保存后立即生效。",
        barHeightDescription: "应用缩放前的世界空间血条高度。保存后立即生效。",
        worldScaleDescription: "世界空间血条缩放。保存后立即生效。",
        displayModeDescription: "血条布局模式：横向血条、身旁竖条或纯数字。保存后立即生效。",
        showHealthNumbersDescription: "在怪物血条上显示当前血量和满血血量文字。保存后立即生效。",
        healthTextFormatDescription: "血量文字格式：当前 / 满血、仅当前血量或仅百分比。保存后立即生效。",
        showEnemyNameDescription: "在血量数字旁显示怪物名称。保存后立即生效。",
        sideBarWidthDescription: "应用缩放前的竖向侧边血条宽度。保存后立即生效。",
        sideBarHeightDescription: "应用缩放前的竖向侧边血条高度。保存后立即生效。",
        sideBarHorizontalOffsetDescription: "身旁竖条模式使用的水平偏移。保存后立即生效。",
        debugEnabledDescription: "启用仅用于测试的调试功能。正常游玩时应保持关闭。保存后立即生效。",
        debugShowFullHealthEnemiesDescription: "仅调试：显示满血怪物血条，用于确认怪物追踪是否工作。需要启用调试模式。保存后立即生效。",
        debugDiagnosticsEnabledDescription: "仅调试：输出低频运行时、相机、扫描和活动血条计数日志。需要启用调试模式。保存后立即生效。",
        debugDiagnosticsLogIntervalDescription: "仅调试：两次诊断日志之间的秒数。保存后立即生效。",
        debugShowTestBarDescription: "仅调试：在活动相机前方渲染固定测试血条。需要启用调试模式。保存后立即生效。");
}
