// <auto-generated />
namespace Auuueser.EnemyHealthBars.Core.GameData;

public static class EnemyHealthDefaults
{
    public const string Source = "Lethal Company_Data; Unity 2022.3.62f2; Assembly-CSharp.dll; assets=41; generator=tools/generate_enemy_health_defaults.py";

    public static readonly EnemyHealthDefault[] Items =
    {
        new EnemyHealthDefault("Baboon hawk", 4),
        new EnemyHealthDefault("Blob", 3),
        new EnemyHealthDefault("Bunker Spider", 5),
        new EnemyHealthDefault("Bush Wolf", 7),
        new EnemyHealthDefault("Butler", 8),
        new EnemyHealthDefault("Butler Bees", 3),
        new EnemyHealthDefault("Cadaver Bloom", 4),
        new EnemyHealthDefault("Cadaver Growths", 3),
        new EnemyHealthDefault("Centipede", 3),
        new EnemyHealthDefault("Clay Surgeon", 3),
        new EnemyHealthDefault("Crawler", 4),
        new EnemyHealthDefault("Docile Locust Bees", 3),
        new EnemyHealthDefault("Earth Leviathan", 3),
        new EnemyHealthDefault("Feiopar", 4),
        new EnemyHealthDefault("Flowerman", 5),
        new EnemyHealthDefault("ForestGiant", 38),
        new EnemyHealthDefault("GiantKiwi", 28),
        new EnemyHealthDefault("Girl", 3),
        new EnemyHealthDefault("Hoarding bug", 3),
        new EnemyHealthDefault("Jester", 3),
        new EnemyHealthDefault("Lasso", 3),
        new EnemyHealthDefault("Maneater", 5),
        new EnemyHealthDefault("Manticoil", 2),
        new EnemyHealthDefault("Masked", 4),
        new EnemyHealthDefault("MouthDog", 12),
        new EnemyHealthDefault("Nutcracker", 5),
        new EnemyHealthDefault("Puffer", 3),
        new EnemyHealthDefault("RadMech", 3),
        new EnemyHealthDefault("Red Locust Bees", 3),
        new EnemyHealthDefault("Red pill", 3),
        new EnemyHealthDefault("Spring", 3),
        new EnemyHealthDefault("Stingray", 4),
        new EnemyHealthDefault("Tulip Snake", 3),
    };
}
